name: Job Bot Daily Run
on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch:      # Allows manual trigger for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib google-generativeai

      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: python main.py
